# 1. non-canonical peptide classification

In [ ]:


from pepbenchmark.model.smiles_model import build_smiles_model
from pepbenchmark.dataset_manager.single_dataset import SinglePeptideDatasetManager



dataset = SinglePeptideDatasetManager(
    "nc-antifungal",
    official_feature_names=["smiles", "label"],
    dataset_dir="../../PepBenchData/PepBenchData-50",
)

# 1) 标准模式
runner_std = build_smiles_model(
    dataset=dataset,
    model_name="seyonec/ChemBERTa-zinc-base-v1",
    task_type="binary_classification",
    smiles_key="smiles",
    label_key="label",
    epochs=50,
    batch_size=64,
    learning_rate=5e-5,
    early_stopping_patience=5,
)


multi_results = runner_std.run_multi(
    run_seeds=[42, 43, 44, 45, 46],
    fold_seeds=[0, 1,2, 3, 4],
    split_type="ecfp_split",
)

print(multi_results.to_dataframe().head())
print(multi_results.get_summary_stats().get("test_roc-auc"))

2026-03-28 11:50:03 | INFO     | pepbenchmark | Loaded official feature: smiles
2026-03-28 11:50:03 | INFO     | pepbenchmark | Loaded official feature: label
2026-03-28 11:50:03 | INFO     | pepbenchmark | [RUN_MULTI] running seed=42, fold=0
2026-03-28 11:50:03 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====0=== successfully

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at seyonec/ChemBERTa-zinc-base-v1 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Token indices sequence length is longer than the specified maximum sequence length for this model (527 > 512). Running this sequence through the model will result in indexing errors

2026-03-28 11:50:08 | WARNING  | pepbenchmark | Requested max_length=655 exceeds tokenizer/model limit 512; clamping to 512.

2026-03-28 11:51:20 | INFO     | pepbenchmark | [RUN_MULTI] running seed=43, fold=1
2026-03-28 11:51:20 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====1=== successfully

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at seyonec/ChemBERTa-zinc-base-v1 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Token indices sequence length is longer than the specified maximum sequence length for this model (538 > 512). Running this sequence through the model will result in indexing errors

2026-03-28 11:51:23 | WARNING  | pepbenchmark | Requested max_length=655 exceeds tokenizer/model limit 512; clamping to 512.

/home/batchcom/assist/miniforge3/envs/pepbenchmark/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

2026-03-28 11:52:45 | INFO     | pepbenchmark | [RUN_MULTI] running seed=44, fold=2
2026-03-28 11:52:45 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====2=== successfully

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at seyonec/ChemBERTa-zinc-base-v1 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Token indices sequence length is longer than the specified maximum sequence length for this model (527 > 512). Running this sequence through the model will result in indexing errors

2026-03-28 11:52:47 | WARNING  | pepbenchmark | Requested max_length=655 exceeds tokenizer/model limit 512; clamping to 512.

2026-03-28 11:54:49 | INFO     | pepbenchmark | [RUN_MULTI] running seed=45, fold=3
2026-03-28 11:54:49 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====3=== successfully

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at seyonec/ChemBERTa-zinc-base-v1 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Token indices sequence length is longer than the specified maximum sequence length for this model (538 > 512). Running this sequence through the model will result in indexing errors

2026-03-28 11:54:52 | WARNING  | pepbenchmark | Requested max_length=655 exceeds tokenizer/model limit 512; clamping to 512.

2026-03-28 11:55:45 | INFO     | pepbenchmark | [RUN_MULTI] running seed=46, fold=4
2026-03-28 11:55:45 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====4=== successfully

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at seyonec/ChemBERTa-zinc-base-v1 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Token indices sequence length is longer than the specified maximum sequence length for this model (538 > 512). Running this sequence through the model will result in indexing errors

2026-03-28 11:55:54 | WARNING  | pepbenchmark | Requested max_length=655 exceeds tokenizer/model limit 512; clamping to 512.

2026-03-28 11:56:48 | INFO     | pepbenchmark | [RUN_MULTI DONE] total runs: 5
   random_seed  fold_seed                      model_name  split_type  \
0           42          0  seyonec/ChemBERTa-zinc-base-v1  ecfp_split
1           43          1  seyonec/ChemBERTa-zinc-base-v1  ecfp_split
2           44          2  seyonec/ChemBERTa-zinc-base-v1  ecfp_split
3           45          3  seyonec/ChemBERTa-zinc-base-v1  ecfp_split
4           46          4  seyonec/ChemBERTa-zinc-base-v1  ecfp_split

   train_samples  valid_samples  test_samples  training_time  train_accuracy  \
0            322             40            41      67.586434        0.500000
1            322             40            41      77.913111        0.885093
2            322             40            41     118.266226        0.978261
3            322             40            41      49.254143        0.832298
4            322             40            41      51.169415        0.841615

   train_balanced-accuracy  ...  test_macro-f1  test_weighted-f1  test_mcc  \
0                 0.559244  ...       0.588629          0.732523  0.276611
1                 0.894928  ...       0.796020          0.874894  0.594423
2                 0.980663  ...       0.711944          0.763352  0.458074
3                 0.850824  ...       0.707143          0.853659  0.414286
4                 0.851279  ...       0.503030          0.609756  0.006061

   test_kappa  test_g-mean  test_roc-auc  test_avg-roc-auc  test_pr-auc  \
0    0.219873     0.439941      0.632258          0.632258     0.456419
1    0.592445     0.766238      0.890152          0.890152     0.655952
2    0.434916     0.654654      0.848901          0.848901     0.666978
3    0.414286     0.676123      0.900000          0.900000     0.633547
4    0.006061     0.447214      0.615152          0.615152     0.465462

   test_brier-score  test_log-loss
0          0.187189       0.561742
1          0.103863       0.330142
2          0.177958       0.717920
3          0.104221       0.318071
4          0.221297       0.624879

[5 rows x 59 columns]
None

In [ ]:


from pepbenchmark.model.smiles_model_pepclm import build_smiles_model
from pepbenchmark.dataset_manager.single_dataset import SinglePeptideDatasetManager



dataset = SinglePeptideDatasetManager(
    "nc-antifungal",
    official_feature_names=["smiles", "label"],
    dataset_dir="../../PepBenchData/PepBenchData-50",
)

# 1) 标准模式
runner_std = build_smiles_model(
    dataset=dataset,
    model_name="aaronfeller/PeptideCLM-23M-all",    
    task_type="binary_classification",
    smiles_key="smiles",
    label_key="label",
    epochs=50,
    batch_size=64,
    learning_rate=5e-5,
    early_stopping_patience=5,
)


multi_results = runner_std.run_multi(
    run_seeds=[42, 43, 44, 45, 46],
    fold_seeds=[0, 1,2, 3, 4],
    split_type="ecfp_split",
)

print(multi_results.to_dataframe().head())
print(multi_results.get_summary_stats().get("test_roc-auc"))

2026-03-28 14:35:36 | INFO     | pepbenchmark | Loaded official feature: smiles
2026-03-28 14:35:36 | INFO     | pepbenchmark | Loaded official feature: label
2026-03-28 14:35:36 | INFO     | pepbenchmark | [RUN_MULTI] running seed=42, fold=0
2026-03-28 14:35:36 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====0=== successfully
2026-03-28 14:35:36 | INFO     | pepbenchmark | Using PeptideCLM custom SMILES-SPE tokenizer.

Some weights of RoFormerForSequenceClassification were not initialized from the model checkpoint at aaronfeller/PeptideCLM-23M-all and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

/home/batchcom/assist/miniforge3/envs/pepbenchmark/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

2026-03-28 14:37:58 | INFO     | pepbenchmark | [RUN_MULTI] running seed=43, fold=1
2026-03-28 14:37:58 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====1=== successfully
2026-03-28 14:37:58 | INFO     | pepbenchmark | Using PeptideCLM custom SMILES-SPE tokenizer.

Some weights of RoFormerForSequenceClassification were not initialized from the model checkpoint at aaronfeller/PeptideCLM-23M-all and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 14:39:24 | INFO     | pepbenchmark | [RUN_MULTI] running seed=44, fold=2
2026-03-28 14:39:24 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====2=== successfully
2026-03-28 14:39:24 | INFO     | pepbenchmark | Using PeptideCLM custom SMILES-SPE tokenizer.

Some weights of RoFormerForSequenceClassification were not initialized from the model checkpoint at aaronfeller/PeptideCLM-23M-all and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 14:40:41 | INFO     | pepbenchmark | [RUN_MULTI] running seed=45, fold=3
2026-03-28 14:40:41 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====3=== successfully
2026-03-28 14:40:41 | INFO     | pepbenchmark | Using PeptideCLM custom SMILES-SPE tokenizer.

Some weights of RoFormerForSequenceClassification were not initialized from the model checkpoint at aaronfeller/PeptideCLM-23M-all and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 14:42:17 | INFO     | pepbenchmark | [RUN_MULTI] running seed=46, fold=4
2026-03-28 14:42:17 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====4=== successfully
2026-03-28 14:42:17 | INFO     | pepbenchmark | Using PeptideCLM custom SMILES-SPE tokenizer.

Some weights of RoFormerForSequenceClassification were not initialized from the model checkpoint at aaronfeller/PeptideCLM-23M-all and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 14:43:38 | INFO     | pepbenchmark | [RUN_MULTI DONE] total runs: 5
   random_seed  fold_seed                      model_name  split_type  \
0           42          0  aaronfeller/PeptideCLM-23M-all  ecfp_split
1           43          1  aaronfeller/PeptideCLM-23M-all  ecfp_split
2           44          2  aaronfeller/PeptideCLM-23M-all  ecfp_split
3           45          3  aaronfeller/PeptideCLM-23M-all  ecfp_split
4           46          4  aaronfeller/PeptideCLM-23M-all  ecfp_split

   train_samples  valid_samples  test_samples  training_time  train_accuracy  \
0            322             40            41     132.017117        0.962733
1            322             40            41      80.692074        0.788820
2            322             40            41      71.481640        0.776398
3            322             40            41      91.012718        0.807453
4            322             40            41      78.009876        0.903727

   train_balanced-accuracy  ...  test_macro-f1  test_weighted-f1  test_mcc  \
0                 0.962889  ...       0.760234          0.826130  0.522093
1                 0.808877  ...       0.632836          0.774809  0.267291
2                 0.800321  ...       0.591855          0.679263  0.305898
3                 0.804945  ...       0.646552          0.750210  0.468025
4                 0.913581  ...       0.666063          0.756649  0.372271

   test_kappa  test_g-mean  test_roc-auc  test_avg-roc-auc  test_pr-auc  \
0    0.520868     0.736163      0.845161          0.845161     0.770612
1    0.266402     0.574060      0.833333          0.833333     0.647096
2    0.239460     0.471728      0.725275          0.725275     0.639487
3    0.359375     0.810643      0.923810          0.923810     0.621164
4    0.346903     0.582575      0.842424          0.842424     0.694106

   test_brier-score  test_log-loss
0          0.125073       0.396784
1          0.114957       0.378873
2          0.194209       0.582334
3          0.178055       0.534313
4          0.165259       0.519010

[5 rows x 59 columns]
None

In [8]:


from pepbenchmark.model.smiles_model_pepdora import build_smiles_model
from pepbenchmark.dataset_manager.single_dataset import SinglePeptideDatasetManager



dataset = SinglePeptideDatasetManager(
    # "nc-antifungal",
    "nc-antibacterial",
    official_feature_names=["smiles", "label"],
    dataset_dir="../../PepBenchData/PepBenchData-50",
)

# 1) 标准模式
runner_std = build_smiles_model(
    dataset=dataset,
    model_name="ChatterjeeLab/PepDoRA",    
    task_type="binary_classification",
    smiles_key="smiles",
    label_key="label",
    epochs=50,
    batch_size=64,
    learning_rate=5e-5,
    early_stopping_patience=5,
)


multi_results = runner_std.run_multi(
    run_seeds=[42, 43, 44, 45, 46],
    fold_seeds=[0, 1,2, 3, 4],
    split_type="ecfp_split",
)

print(multi_results.to_dataframe().head())
print(multi_results.get_summary_stats().get("test_roc-auc"))

2026-03-28 15:09:18 | INFO     | pepbenchmark | Loaded official feature: smiles
2026-03-28 15:09:18 | INFO     | pepbenchmark | Loaded official feature: label
2026-03-28 15:09:18 | INFO     | pepbenchmark | [RUN_MULTI] running seed=42, fold=0
2026-03-28 15:09:18 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====0=== successfully

Some weights of RobertaModel were not initialized from the model checkpoint at DeepChem/ChemBERTa-77M-MLM and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 15:09:22 | INFO     | pepbenchmark | Loaded PepDoRA backbone using direct AutoModel mode.

Token indices sequence length is longer than the specified maximum sequence length for this model (559 > 512). Running this sequence through the model will result in indexing errors

2026-03-28 15:09:24 | WARNING  | pepbenchmark | Requested max_length=962 exceeds tokenizer/model limit 512; clamping to 512.

2026-03-28 15:10:01 | INFO     | pepbenchmark | [RUN_MULTI] running seed=43, fold=1
2026-03-28 15:10:01 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====1=== successfully

Some weights of RobertaModel were not initialized from the model checkpoint at DeepChem/ChemBERTa-77M-MLM and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 15:10:13 | INFO     | pepbenchmark | Loaded PepDoRA backbone using direct AutoModel mode.

Token indices sequence length is longer than the specified maximum sequence length for this model (559 > 512). Running this sequence through the model will result in indexing errors

2026-03-28 15:10:15 | WARNING  | pepbenchmark | Requested max_length=962 exceeds tokenizer/model limit 512; clamping to 512.

2026-03-28 15:10:47 | INFO     | pepbenchmark | [RUN_MULTI] running seed=44, fold=2
2026-03-28 15:10:47 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====2=== successfully

Some weights of RobertaModel were not initialized from the model checkpoint at DeepChem/ChemBERTa-77M-MLM and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 15:10:51 | INFO     | pepbenchmark | Loaded PepDoRA backbone using direct AutoModel mode.

Token indices sequence length is longer than the specified maximum sequence length for this model (559 > 512). Running this sequence through the model will result in indexing errors

2026-03-28 15:10:53 | WARNING  | pepbenchmark | Requested max_length=962 exceeds tokenizer/model limit 512; clamping to 512.

2026-03-28 15:11:27 | INFO     | pepbenchmark | [RUN_MULTI] running seed=45, fold=3
2026-03-28 15:11:27 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====3=== successfully

Some weights of RobertaModel were not initialized from the model checkpoint at DeepChem/ChemBERTa-77M-MLM and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 15:11:31 | INFO     | pepbenchmark | Loaded PepDoRA backbone using direct AutoModel mode.

Token indices sequence length is longer than the specified maximum sequence length for this model (559 > 512). Running this sequence through the model will result in indexing errors

2026-03-28 15:11:32 | WARNING  | pepbenchmark | Requested max_length=962 exceeds tokenizer/model limit 512; clamping to 512.

2026-03-28 15:12:07 | INFO     | pepbenchmark | [RUN_MULTI] running seed=46, fold=4
2026-03-28 15:12:07 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====4=== successfully

Some weights of RobertaModel were not initialized from the model checkpoint at DeepChem/ChemBERTa-77M-MLM and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 15:12:11 | INFO     | pepbenchmark | Loaded PepDoRA backbone using direct AutoModel mode.

Token indices sequence length is longer than the specified maximum sequence length for this model (559 > 512). Running this sequence through the model will result in indexing errors

2026-03-28 15:12:13 | WARNING  | pepbenchmark | Requested max_length=962 exceeds tokenizer/model limit 512; clamping to 512.

'(ReadTimeoutError("HTTPSConnectionPool(host='hf-mirror.com', port=443): Read timed out. (read timeout=10)"), '(Request ID: c29d61d9-64ec-4628-b84e-0b89897a4e8c)')' thrown while requesting HEAD https://hf-mirror.com/DeepChem/ChemBERTa-77M-MLM/resolve/main/config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='hf-mirror.com', port=443): Read timed out. (read timeout=10)"), '(Request ID: c29d61d9-64ec-4628-b84e-0b89897a4e8c)')' thrown while requesting HEAD https://hf-mirror.com/DeepChem/ChemBERTa-77M-MLM/resolve/main/config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

2026-03-28 15:12:58 | INFO     | pepbenchmark | [RUN_MULTI DONE] total runs: 5
   random_seed  fold_seed             model_name  split_type  train_samples  \
0           42          0  ChatterjeeLab/PepDoRA  ecfp_split           1315
1           43          1  ChatterjeeLab/PepDoRA  ecfp_split           1315
2           44          2  ChatterjeeLab/PepDoRA  ecfp_split           1315
3           45          3  ChatterjeeLab/PepDoRA  ecfp_split           1315
4           46          4  ChatterjeeLab/PepDoRA  ecfp_split           1315

   valid_samples  test_samples  training_time  train_accuracy  \
0            164           165      28.442062        0.427376
1            164           165      25.961693        0.622053
2            164           165      26.246689        0.554373
3            164           165      27.353140        0.498859
4            164           165      26.356482        0.607605

   train_balanced-accuracy  ...  test_macro-f1  test_weighted-f1  test_mcc  \
0                 0.476280  ...       0.409259          0.680382 -0.174426
1                 0.564315  ...       0.383440          0.415463  0.065676
2                 0.521863  ...       0.451191          0.538456  0.209135
3                 0.458039  ...       0.299806          0.356002 -0.089188
4                 0.525096  ...       0.176965          0.112060  0.008503

   test_kappa  test_g-mean  test_roc-auc  test_avg-roc-auc  test_pr-auc  \
0   -0.167358     0.180154      0.326393          0.326393     0.101024
1    0.036650     0.478632      0.559915          0.559915     0.217622
2    0.120164     0.599941      0.624409          0.624409     0.197391
3   -0.042683     0.400000      0.549143          0.549143     0.191867
4    0.001535     0.203728      0.441339          0.441339     0.155872

   test_brier-score  test_log-loss
0          0.239167       0.671415
1          0.260603       0.714403
2          0.257938       0.709084
3          0.259645       0.712465
4          0.277073       0.747525

[5 rows x 59 columns]
{'mean': 0.5002399263777868, 'std': 0.10494056513827729, 'min': 0.3263931414574403, 'max': 0.6244089834515366}

# 2. non-canonical peptide regression

In [ ]:
from pepbenchmark.model.smiles_model import build_smiles_model
from pepbenchmark.dataset_manager.single_dataset import SinglePeptideDatasetManager


dataset = SinglePeptideDatasetManager(
    "nc-cpp_pampa",
    official_feature_names=["smiles", "label"],
    dataset_dir="../../PepBenchData/PepBenchData-50",
)
runner = build_smiles_model(
    dataset=dataset,
    model_name="seyonec/ChemBERTa-zinc-base-v1",
    task_type="regression",
    smiles_key="smiles",
    label_key="label",
    epochs=50,
    batch_size=64,
    learning_rate=5e-5,
    early_stopping_patience=5,
)

multi_results = runner.run_multi(
    run_seeds=[42, 43, 44, 45, 46],
    fold_seeds=[0, 1, 2, 3, 4],
    split_type="ecfp_split",   
)
print(multi_results.to_dataframe())
summary = multi_results.get_summary_stats()
print(summary["test_mae"])

2026-03-28 13:53:35 | INFO     | pepbenchmark | Loaded official feature: smiles
2026-03-28 13:53:35 | INFO     | pepbenchmark | Loaded official feature: label
2026-03-28 13:53:35 | INFO     | pepbenchmark | [RUN_MULTI] running seed=42, fold=0
2026-03-28 13:53:35 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====0=== successfully

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at seyonec/ChemBERTa-zinc-base-v1 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 13:57:50 | INFO     | pepbenchmark | [RUN_MULTI] running seed=43, fold=1
2026-03-28 13:57:50 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====1=== successfully

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at seyonec/ChemBERTa-zinc-base-v1 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

2026-03-28 14:03:50 | INFO     | pepbenchmark | [RUN_MULTI] running seed=44, fold=2
2026-03-28 14:03:50 | INFO     | pepbenchmark | Set official split ===ecfp_split=== with seed ====2=== successfully

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at seyonec/ChemBERTa-zinc-base-v1 and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.